import type { Locale } from "./routing";
export type ChromeLabels = {
  nav: string[]; contact: string; home: string; navigation: string; open: string; close: string;
  language: string; dark: string; light: string;
  footer: { description: string; services: string; company: string; location: string; projects: string; products: string; privacy: string; legal: string; country: string };
};
export type ContactLabels = {
  name: string; email: string; company: string; optional: string; message: string; privacy: string;
  directHint: string; emailHint: string; sending: string; send: string; prepare: string;
  prepared: string; sent: string; error: string; subject: string;
  introTitle: string; introBody: string; successTitle: string; sendAnother: string;
};
export const ui: Record<Locale, { chrome: ChromeLabels; contact: ContactLabels }> = {
  de: {
    chrome: { nav: ["IT Services", "Beratung & Projekte", "Software & Portale", "KI & Automatisierung", "Unternehmen", "Karriere"], contact: "Kontakt", home: "Edasan Startseite", navigation: "Hauptnavigation", open: "Navigation öffnen", close: "Navigation schliessen", language: "Sprache wählen", dark: "Dunklen Modus aktivieren", light: "Hellen Modus aktivieren", footer: { description: "IT Services, Beratung und Software für Unternehmen in der Schweiz.", services: "Leistungen", company: "Edasan", location: "Standort & Kontakt", projects: "Projekte & Erfahrung", products: "Eigenentwicklungen", privacy: "Datenschutz", legal: "Impressum", country: "Schweiz" } },
    contact: { name: "Name", email: "E-Mail-Adresse", company: "Unternehmen", optional: "(optional)", message: "Ihr Anliegen", privacy: "Datenschutz", directHint: "Ihre Angaben werden zur Bearbeitung der Anfrage an uns übermittelt.", emailHint: "Das Formular öffnet Ihr E-Mail-Programm mit einer vorbereiteten Nachricht. Bitte senden Sie diese dort ab.", sending: "Wird gesendet …", send: "Anfrage senden", prepare: "E-Mail vorbereiten", prepared: "Bitte senden Sie die vorbereitete Nachricht in Ihrem E-Mail-Programm ab. Falls es sich nicht geöffnet hat, schreiben Sie direkt an", sent: "Ihre Anfrage ist bei uns eingegangen. Wir melden uns so schnell wie möglich bei Ihnen.", error: "Die Übermittlung konnte nicht bestätigt werden. Bitte schreiben Sie direkt an", subject: "Anfrage über die Edasan Website", introTitle: "Erzählen Sie uns von Ihrem Vorhaben.", introBody: "Ein paar Sätze zur Ausgangslage reichen für den Anfang.", successTitle: "Vielen Dank für Ihre Nachricht.", sendAnother: "Weitere Nachricht senden" },
  },
  fr: {
    chrome: { nav: ["Services IT", "Conseil & projets", "Logiciels & portails", "IA & automatisation", "Entreprise", "Carrières"], contact: "Contact", home: "Accueil Edasan", navigation: "Navigation principale", open: "Ouvrir la navigation", close: "Fermer la navigation", language: "Choisir la langue", dark: "Activer le mode sombre", light: "Activer le mode clair", footer: { description: "Services IT, conseil et logiciels pour les entreprises en Suisse.", services: "Prestations", company: "Edasan", location: "Localisation & contact", projects: "Projets & expérience", products: "Nos développements", privacy: "Protection des données", legal: "Mentions légales", country: "Suisse" } },
    contact: { name: "Nom", email: "Adresse e-mail", company: "Entreprise", optional: "(facultatif)", message: "Votre demande", privacy: "Protection des données", directHint: "Vos informations nous sont transmises pour traiter votre demande.", emailHint: "Le formulaire ouvre votre messagerie avec un message préparé. Veuillez l'envoyer depuis votre messagerie.", sending: "Envoi en cours …", send: "Envoyer la demande", prepare: "Préparer l'e-mail", prepared: "Veuillez envoyer le message préparé depuis votre messagerie. Si elle ne s'est pas ouverte, écrivez directement à", sent: "Nous avons bien reçu votre demande. Nous vous recontacterons dans les meilleurs délais.", error: "L'envoi n'a pas pu être confirmé. Veuillez écrire directement à", subject: "Demande via le site Edasan", introTitle: "Parlez-nous de votre projet.", introBody: "Quelques phrases sur votre situation suffisent pour commencer.", successTitle: "Merci pour votre message.", sendAnother: "Envoyer un autre message" },
  },
  en: {
    chrome: { nav: ["IT services", "Consulting & projects", "Software & portals", "AI & automation", "Company", "Careers"], contact: "Contact", home: "Edasan home", navigation: "Main navigation", open: "Open navigation", close: "Close navigation", language: "Choose language", dark: "Switch to dark mode", light: "Switch to light mode", footer: { description: "IT services, consulting and software for businesses in Switzerland.", services: "Services", company: "Edasan", location: "Location & contact", projects: "Projects & experience", products: "Our own products", privacy: "Privacy", legal: "Legal notice", country: "Switzerland" } },
    contact: { name: "Name", email: "Email address", company: "Company", optional: "(optional)", message: "Your enquiry", privacy: "Privacy", directHint: "Your information will be sent to us to handle your enquiry.", emailHint: "The form opens your email app with a prepared message. Please send it from there.", sending: "Sending …", send: "Send enquiry", prepare: "Prepare email", prepared: "Please send the prepared message from your email app. If it did not open, write directly to", sent: "We have received your enquiry. We will get back to you as soon as possible.", error: "Delivery could not be confirmed. Please write directly to", subject: "Enquiry via the Edasan website", introTitle: "Tell us about your project.", introBody: "A few sentences about your situation are enough to get started.", successTitle: "Thank you for your message.", sendAnother: "Send another message" },
  },
  it: {
    chrome: { nav: ["Servizi IT", "Consulenza & progetti", "Software & portali", "IA & automazione", "Azienda", "Carriera"], contact: "Contatti", home: "Homepage Edasan", navigation: "Navigazione principale", open: "Aprire la navigazione", close: "Chiudere la navigazione", language: "Scegliere la lingua", dark: "Attivare il tema scuro", light: "Attivare il tema chiaro", footer: { description: "Servizi IT, consulenza e software per le aziende in Svizzera.", services: "Servizi", company: "Edasan", location: "Sede & contatti", projects: "Progetti & esperienza", products: "Sviluppi propri", privacy: "Protezione dei dati", legal: "Note legali", country: "Svizzera" } },
    contact: { name: "Nome", email: "Indirizzo e-mail", company: "Azienda", optional: "(facoltativo)", message: "La vostra richiesta", privacy: "Protezione dei dati", directHint: "I vostri dati ci saranno trasmessi per gestire la richiesta.", emailHint: "Il modulo apre il programma di posta con un messaggio preparato. Inviatelo dal programma di posta.", sending: "Invio in corso …", send: "Inviare la richiesta", prepare: "Preparare l'e-mail", prepared: "Inviate il messaggio preparato dal programma di posta. Se non si è aperto, scrivete direttamente a", sent: "Abbiamo ricevuto la vostra richiesta. Vi ricontatteremo il prima possibile.", error: "Non è stato possibile confermare l'invio. Scrivete direttamente a", subject: "Richiesta dal sito Edasan", introTitle: "Raccontateci il vostro progetto.", introBody: "Per iniziare bastano poche frasi sulla vostra situazione.", successTitle: "Grazie per il vostro messaggio.", sendAnother: "Inviare un altro messaggio" },
  },
};
